### PR TITLE
Fixed slices requesting ranges

### LINKED ISSUE #644: Incorrect slices loading
## Expected Behavior

Loading slices to the lower boundary without "jumping" up in slices series. Introduce some kind of wait mechanism to eliminate slices scramble possibility.

## Steps to Reproduce the Problem

  1. Get to the labelling page
  2. Quickly scroll down (constant scrolling with mouse or keep keyboard arrow button clicked)
  3. Voila

### PR DESCRIPTION
**Pull request by Darkoon**
Fixes #644

## Proposed Changes

  - _Corrected slice request range (previous one omitted one image)_
  - _Fixed slider jumping in transition from slice 1 -> 0_
  - _Added cleanup before scan request_
  - _Blocked sending and skipping buttons to avoid slices mixing up_

### CODE REVIEW

File: frontend/src/app/components/scan-viewer/scan-viewer.component.ts [hunk 1]
```diff
@@ -316,7 +319,7 @@ export class ScanViewerComponent implements OnInit, AfterViewInit, OnChanges {
     }
 
     protected createDrawingContext(): DrawingContext {
-        const currentSlice = this.currentSlice || this.slices.keys().next().value;
+        const currentSlice = this.currentSlice;
```
Comment (jpowie01) [inline frontend/src/app/components/scan-viewer/scan-viewer.component.ts]: This line doesn't make any sense now 😛
